# Generated by Django 5.1.3 on 2024-11-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='qrcode',
        ),
    ]
