# Generated by Django 5.1.3 on 2024-11-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_contact_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='media/qrcodes/'),
        ),
    ]
