# Generated by Django 5.1.3 on 2024-11-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_contact_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/'),
        ),
    ]
