# Generated by Django 5.1.3 on 2024-11-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_identity_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='identity',
            name='last_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
