# Generated by Django 5.1.3 on 2024-11-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_rename_name_identity_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='validity_time',
            field=models.DateField(),
        ),
    ]
