# Generated by Django 5.1.3 on 2024-11-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_flyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
