# Generated by Django 5.1.3 on 2024-11-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_flyer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='work',
            field=models.CharField(choices=[('isstaff', 'Is Staff'), ('notstaff', 'Not Staff')], default='notstaff', max_length=10),
        ),
    ]
